"""Build assets/two-cultures-data.js from the UCI Breast Cancer Wisconsin (Diagnostic) data.

Source: the copy bundled with scikit-learn (sklearn.datasets.load_breast_cancer), which is
byte-for-byte the UCI file wdbc.data (checked 2026-09-29: max abs difference 0.0, labels equal).
Wolberg, W., Mangasarian, O., Street, N., & Street, W. (1993). Breast Cancer Wisconsin
(Diagnostic) [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C5DW2B
Licence CC BY 4.0.

Every value is shipped EXACTLY: each column is stored as integers scaled by 10^dec, where dec
is the number of decimals the UCI file prints for that column. value = int / 10**dec in both
Python and JavaScript gives the identical IEEE double.

The train/test split is fixed here, once, stratified by class, seed 2001, 30 percent held out,
and shipped as an explicit list of row indices so the browser never has to reproduce numpy's
generator.

Run from the repo root:  python3 materials/build-wdbc-sample.py
"""
import json
from decimal import Decimal
from pathlib import Path

import numpy as np
from sklearn.datasets import load_breast_cancer

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "two-cultures-data.js"

d = load_breast_cancer()
X, y = d.data, d.target  # target 1 = benign, 0 = malignant (sklearn convention)
names = [str(n) for n in d.feature_names]
n, p = X.shape
assert (n, p) == (569, 30)

# decimals per column: the smallest dec that reproduces every value exactly
dec = []
for j in range(p):
    k = 0
    while k < 8:
        s = 10 ** k
        if all(float(Decimal(repr(v)) * s) == round(v * s) for v in X[:, j]) and all(
            round(v * s) / s == v for v in X[:, j]
        ):
            break
        k += 1
    dec.append(k)

ints = [[int(round(X[i, j] * 10 ** dec[j])) for j in range(p)] for i in range(n)]
for i in range(n):
    for j in range(p):
        assert ints[i][j] / 10 ** dec[j] == X[i, j], (i, j)

rng = np.random.default_rng(2001)
test = []
for cls in (0, 1):
    idx = np.flatnonzero(y == cls)
    perm = rng.permutation(idx)
    k = int(round(0.30 * len(idx)))
    test.extend(int(v) for v in perm[:k])
test = sorted(test)

# the creators' own three features (wdbc.names, "Results"): Worst Area, Worst Smoothness,
# Mean Texture, one separating plane, estimated accuracy 97.5% by repeated 10-fold CV.
NAMED3 = [names.index("worst area"), names.index("worst smoothness"), names.index("mean texture")]

payload = {
    "source": "UCI Breast Cancer Wisconsin (Diagnostic), Wolberg, Street and Mangasarian, doi 10.24432/C5DW2B, CC BY 4.0",
    "n": n,
    "p": p,
    "names": names,
    "dec": dec,
    "y": [int(v) for v in y],
    "classes": ["malignant", "benign"],
    "test": test,
    "named3": NAMED3,
    "split_seed": 2001,
    "X": ints,
}

body = (
    "/* two-cultures-data.js - the 569 real biopsies of the UCI Breast Cancer Wisconsin (Diagnostic)\n"
    " * dataset (Wolberg, Street, Mangasarian; doi 10.24432/C5DW2B; CC BY 4.0), 30 features each.\n"
    " * X holds integers: value = X[i][j] / 10^dec[j], exact. y: 1 = benign, 0 = malignant.\n"
    " * test = the 171 held-out rows (stratified, seed 2001). Generated by\n"
    " * materials/build-wdbc-sample.py with json.dumps; do not edit by hand. */\n"
    "window.TC_DATA = " + json.dumps(payload, separators=(",", ":")) + ";\n"
)
OUT.write_text(body)
print(f"wrote {OUT} ({OUT.stat().st_size:,} bytes); n={n} p={p} test={len(test)} "
      f"test benign={sum(y[i] for i in test)} train={n-len(test)}; dec={dec}")
